services:
  api:
    container_name: reg_helper_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - NODE_ENV
      - ACCESS_SECRET
      - ACCESS_EXPIRES_IN
      - DATABASE_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
    ports:
      - '${PORT}:${PORT}'
    networks:
      - api_network
    restart: always
    command: sh -c "npx prisma migrate deploy && node dist/main"

networks:
  api_network:
    driver: bridge
