services:
  api:
    container_name: reg_helper_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT
      - NODE_ENV
      - ACCESS_SECRET
      - ACCESS_EXPIRES_IN
    ports:
      - '${PORT}:${PORT}'
    networks:
      - api_network

networks:
  api_network:
    driver: bridge
