name: CD

on:
  workflow_run:
    workflows: ['CI']
    branches: ['main']
    types:
      - completed

env:
  PORT: ${{ secrets.PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  ACCESS_EXPIRES_IN: ${{ secrets.ACCESS_EXPIRES_IN }}
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  MINIO_ENDPOINT: ${{ secrets.MINIO_ENDPOINT }}
  MINIO_BUCKET: ${{ secrets. MINIO_BUCKET }}
  MINIO_PORT: ${{ secrets.MINIO_PORT }}
  MINIO_ACCESS_KEY: ${{ secrets.MINIO_ACCESS_KEY }}
  MINIO_SECRET_KEY: ${{ secrets.MINIO_SECRET_KEY }}
  MINIO_USE_SSL: ${{ secrets.MINIO_USE_SSL }}
  OAUTH_REDIRECT_URL: ${{ secrets.OAUTH_REDIRECT_URL }}

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    if: ${{
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event == 'push'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy docker-compose stack
        run: docker compose up -d --build --force-recreate

      - name: Prune Docker system
        run: docker system prune -af
