name: CD

on:
  workflow_run:
    workflows: ['CI']
    branches: ['main']
    types:
      - completed

env:
  PORT: ${{ secrets.PORT }}
  NODE_ENV: ${{ secrets.NODE_ENV }}
  ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
  ACCESS_EXPIRES_IN: ${{ secrets.ACCESS_EXPIRES_IN }}

jobs:
  deploy:
    name: deploy
    runs-on: self-hosted
    if: ${{
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event == 'push'
      }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy docker-compose stack
        run: docker compose up -d --build --force-recreate

      - name: Prune Docker system
        run: docker system prune -af
